version: '3.1'

services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sk123

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes: